# Prepare Qt

if(USE_QT5)
  set(USE_QT5_01 1)
  if(Qt5_INSTALL_DIR)
    set(Qt5_DIR "${Qt5_INSTALL_DIR}/lib/cmake/Qt5")
  endif()
else()
  set(USE_QT5_01 0)
endif()

if(USE_QT6)
  set(USE_QT6_01 1)
  if(Qt6_INSTALL_DIR)
    set(Qt6_DIR "${Qt6_INSTALL_DIR}/lib/cmake/Qt6")
  endif()
else()
  set(USE_QT6_01 0)
endif()

macro(PREPARE_QT4 MINIMUM_VERSION)
  set(_MODULE_NAMES ${ARGN})
  set(QT_VER 4)
  foreach(_MODULE_NAME ${_MODULE_NAMES})
    list(APPEND _QT_MODULE_NAMES "Qt${_MODULE_NAME}")
    if(WIN32)
      list(APPEND QT_USED_DLL_NAMES "${_MODULE_NAME}")
    endif()
  endforeach()
  find_package(Qt4 ${MINIMUM_VERSION} REQUIRED ${_QT_MODULE_NAMES})
  if(NOT QT4_FOUND)
    message(FATAL_ERROR "Cannot find Qt ${MINIMUM_VERSION} or greater!")
    set(QT_PREPARED FALSE)
  else()
    include(${QT_USE_FILE})
    set(QT_USED_DLL_DIR ${QT_BINARY_DIR})
    if(QT4_NO_LINK_QTMAIN)
      set(QT_USED_LIBRARIES ${QT_LIBRARIES})
    else()
      set(QT_USED_LIBRARIES ${QT_LIBRARIES} ${QT_QTMAIN_LIBRARY})
    endif()
    set(QT_PREPARED TRUE)
  endif()
endmacro()

macro(PREPARE_QT5)
  #set(QT5_DIR "" CACHE PATH "Qt 5 directory.")
  #set(CMAKE_PREFIX_PATH ${QT5_DIR} ${CMAKE_PREFIX_PATH})
  #if(WIN32)
    #find_package(WindowsSDK QUIET)
    #if(WINSDK_FOUND)
    #  message(STATUS "WINSDK_DIR: ${WINSDK_DIR}!")
    #  set(CMAKE_PREFIX_PATH ${WINSDK_DIR} ${CMAKE_PREFIX_PATH})
    #endif(WINSDK_FOUND)
  #endif(WIN32)
  #set(CMAKE_AUTOMOC ON)
  #set(CMAKE_INCLUDE_CURRENT_DIR ON)
  set(_MODULE_NAMES ${ARGN})
  find_package(Qt5 REQUIRED COMPONENTS ${_MODULE_NAMES})
  set(QT_VER 5)
  foreach(_MODULE_NAME ${_MODULE_NAMES})
    list(APPEND _QT_MODULE_NAMES "Qt5${_MODULE_NAME}")
    if(NOT "${_MODULE_NAME}" MATCHES "LinguistTools")
      #message(STATUS "${_MODULE_NAME}!")
      list(APPEND QT_USED_LIBRARIES "Qt5::${_MODULE_NAME}")
      if(WIN32)
        list(APPEND QT_USED_DLL_NAMES "${_MODULE_NAME}")
      endif()
    endif()
  endforeach()
  
  #set(QT5_FOUND TRUE)
  #foreach(_QT_MODULE_NAME ${_QT_MODULE_NAMES})
  #  find_package(${_QT_MODULE_NAME})
  #  if(NOT ${_QT_MODULE_NAME}_FOUND)
  #    set(QT5_FOUND FALSE)
  #    message(FATAL_ERROR "${_QT_MODULE_NAME} not found!")
  #  endif(NOT ${_QT_MODULE_NAME}_FOUND)
  #endforeach(_QT_MODULE_NAME)

  if(NOT Qt5_FOUND)
    message(FATAL_ERROR "Cannot prepare Qt 5!")
    set(QT_PREPARED FALSE)
  else()
    set(QT_PREPARED TRUE)
    set(QT_PLUGINS_DIR ${Qt5_INSTALL_DIR}/plugins)
    set(QT_LIBRARY_DIRS ${Qt5_INSTALL_DIR}/lib)
    set(QT_USED_DLL_DIR ${Qt5_INSTALL_DIR}/bin)
    set(QT_TRANSLATIONS_DIR ${Qt5_INSTALL_DIR}/translations)
    #QT5_USE_MODULES(${TARGETNAME} ${_MODULE_NAMES})
    #message(STATUS "QT_LIBRARY_DIRS: " ${QT_LIBRARY_DIRS})
  endif()
  #get_target_property(UIC_LOCATION Qt5::uic IMPORTED_LOCATION)
  #message(STATUS "UIC_LOCATION: " ${UIC_LOCATION})
endmacro()

macro(PREPARE_QT6)
  set(_MODULE_NAMES ${ARGN})
  find_package(Qt6 REQUIRED COMPONENTS ${_MODULE_NAMES})
  set(QT_VER 6)
  foreach(_MODULE_NAME ${_MODULE_NAMES})
    list(APPEND _QT_MODULE_NAMES "Qt6${_MODULE_NAME}")
    if(NOT "${_MODULE_NAME}" MATCHES "LinguistTools")
      #message(STATUS "${_MODULE_NAME}!")
      list(APPEND QT_USED_LIBRARIES "Qt6::${_MODULE_NAME}")
      if(WIN32)
        list(APPEND QT_USED_DLL_NAMES "${_MODULE_NAME}")
      endif()
    endif()
  endforeach()
  
  #set(QT5_FOUND TRUE)
  #foreach(_QT_MODULE_NAME ${_QT_MODULE_NAMES})
  #  find_package(${_QT_MODULE_NAME})
  #  if(NOT ${_QT_MODULE_NAME}_FOUND)
  #    set(QT5_FOUND FALSE)
  #    message(FATAL_ERROR "${_QT_MODULE_NAME} not found!")
  #  endif(NOT ${_QT_MODULE_NAME}_FOUND)
  #endforeach(_QT_MODULE_NAME)

  if(NOT Qt6_FOUND)
    message(FATAL_ERROR "Cannot prepare Qt 6!")
    set(QT_PREPARED FALSE)
  else()
    set(QT_PREPARED TRUE)
    set(QT_PLUGINS_DIR ${Qt6_INSTALL_DIR}/plugins)
    set(QT_LIBRARY_DIRS ${Qt6_INSTALL_DIR}/lib)
    set(QT_USED_DLL_DIR ${Qt6_INSTALL_DIR}/bin)
    set(QT_TRANSLATIONS_DIR ${Qt6_INSTALL_DIR}/translations)
    #QT5_USE_MODULES(${TARGETNAME} ${_MODULE_NAMES})
    #message(STATUS "QT_LIBRARY_DIRS: " ${QT_LIBRARY_DIRS})
  endif()
  #get_target_property(UIC_LOCATION Qt5::uic IMPORTED_LOCATION)
  #message(STATUS "UIC_LOCATION: " ${UIC_LOCATION})
endmacro()

function(QT_WRAP_CPP_NEW outfiles)
  if(USE_QT5)
    QT5_WRAP_CPP(${outfiles} ${ARGN})
  elseif(USE_QT6)
    QT6_WRAP_CPP(${outfiles} ${ARGN})
  else()
    QT4_WRAP_CPP(${outfiles} ${ARGN})
  endif()
  set(${outfiles} ${${outfiles}} PARENT_SCOPE)
endfunction()

function(QT_WRAP_UI_NEW outfiles)
  if(USE_QT5)
    QT5_WRAP_UI(${outfiles} ${ARGN})
  elseif(USE_QT6)
    QT6_WRAP_UI(${outfiles} ${ARGN})
  else()
    QT4_WRAP_UI(${outfiles} ${ARGN})
  endif()
  set(${outfiles} ${${outfiles}} PARENT_SCOPE)
endfunction()

function(QT_ADD_TRANSLATION_NEW outfiles)
  if(USE_QT5)
    QT5_ADD_TRANSLATION(${outfiles} ${ARGN})
  elseif(USE_QT6)
    QT6_ADD_TRANSLATION(${outfiles} ${ARGN})
  else()
    QT4_ADD_TRANSLATION(${outfiles} ${ARGN})
  endif()
  set(${outfiles} ${${outfiles}} PARENT_SCOPE)
endfunction()

function(QT_ADD_RESOURCES_NEW outfiles)
  if(USE_QT5)
    QT5_ADD_RESOURCES(${outfiles} ${ARGN})
  elseif(USE_QT6)
    QT6_ADD_RESOURCES(${outfiles} ${ARGN})
  else()
    QT4_ADD_RESOURCES(${outfiles} ${ARGN})
  endif()
  set(${outfiles} ${${outfiles}} PARENT_SCOPE)
endfunction()
